{{- if .Values.controller.dockerConfigSecret -}}
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ template "jenkins.fullname" . }}-docker-config
  namespace: {{ template "jenkins.namespace" . }}
  labels:
    "app.kubernetes.io/name": '{{ template "jenkins.name" .}}'
    {{- if .Values.renderHelmLabels }}
    "helm.sh/chart": "{{ template "jenkins.label" .}}"
    {{- end }}
    "app.kubernetes.io/managed-by": "{{ .Release.Service }}"
    "app.kubernetes.io/instance": "{{ .Release.Name }}"
    "app.kubernetes.io/component": "{{ .Values.controller.componentName }}"
data:
  config.json: >-
    {{ .Values.controller.dockerConfigSecret }}
type: Opaque
{{- end }}